### ISSUE TITLE
add support for touch input

### ISSUE THREAD

**Issue by emiyalee1005** [opensourceBIM/BIMsurfer-before2019#177] opened 2016-11-25 10:05 UTC
##### Description of the problem 

camera control is not working on mobile devices,which user input event is touch not mouse

##### bimsurfer version

- [ ] Dev
- [x] Master
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [x] IOS

**Comment by xeolabs** [comment] 2016-11-25 12:20
Yeah will be in there soon. This issue is a duplicate of https://github.com/opensourceBIM/BIMsurfer/issues/157

**Closed as completed by xeolabs** 2016-11-25 12:20 UTC
