### ISSUE TITLE
example_glTF.html is going to show nothing

### ISSUE THREAD

**Issue by dbinkert** [opensourceBIM/BIMsurfer-before2019#193] opened 2017-02-21 13:20 UTC
Hi,
I'm trying out your demo http://opensourcebim.github.io/BIMsurfer/demo/example_glTF.html.
But the browser is not going to show any model.
If I download the source and try it locally, the the same effect is affected.

So how can I use the BIMsurfer standalone with glTF?
 
thank you

**Comment by aothms** [comment] 2017-02-23 13:48
The glTF loader is not tested as regularly as the BIMserver loader. I believe the issue is fixed with 6aa9fe81d237a547ca91c12668a7afa28337a596 and 71c49db18cbdaa71eaba3768c12eaca2d91f9ff7. Let me know if you encounter further issues.

Kind regards,
Thomas

**Closed as completed** 2017-02-23 13:49 UTC

**Comment by dbinkert** [comment] 2017-02-23 17:11
Hi Thomas
Thanks for your response.
The changes seems to be not successful. Now, a never ending loading spinner is displayed.

Kind regards,
Derrin

**Comment by aothms** [comment] 2017-02-27 09:10
So, then the typical questions apply: What browser are you using, what errors/messages are displayed in the javascript console?

Kind regards,
Thomas

**Comment by dbinkert** [comment] 2017-03-01 08:23
Hi Thomas, 

I looked into the javascript console and I detected a cross origin failure. 
I could correct this in my infrastructure. So the example works now.
Thx

Kind regards,
Derrin
